"""Constants for Google Maps Integration."""
from datetime import timedelta

DOMAIN = "google_maps"
ATTRIBUTION = "Data from Google Maps"
NAME_PREFIX = "Google Maps"

CREDENTIALS_FILE = ".google_maps_location_sharing.cookies"

DEF_SCAN_INTERVAL_SEC = 60
DEF_SCAN_INTERVAL = timedelta(seconds=DEF_SCAN_INTERVAL_SEC)
COOKIE_WARNING_PERIOD = timedelta(weeks=4)

HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_PAYLOAD_TOO_LARGE = 413
HTTP_TOO_MANY_REQUESTS = 429
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_BAD_GATEWAY = 502
HTTP_SERVER_UNAVAILABLE = 503

AUTH_ERRORS = (HTTP_FORBIDDEN, HTTP_UNAUTHORIZED)
RETRIES_TOTAL = 5
RETRIES_STATUSES = frozenset(
    {
        HTTP_BAD_GATEWAY,
        HTTP_INTERNAL_SERVER_ERROR,
        HTTP_PAYLOAD_TOO_LARGE,
        HTTP_SERVER_UNAVAILABLE,
        HTTP_TOO_MANY_REQUESTS,
    }
)
RETRIES_BACKOFF = 0.25

ATTR_ADDRESS = "address"
ATTR_FULL_NAME = "full_name"
ATTR_LAST_SEEN = "last_seen"
ATTR_NICKNAME = "nickname"

CONF_COOKIES_FILE = "cookies_file"
CONF_CREATE_ACCT_ENTITY = "create_acct_entity"
CONF_MAX_GPS_ACCURACY = "max_gps_accuracy"
